---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../charts
helmCharts:
- name: wnodeconfig
  repo: ./worker-node-config



# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# helmCharts:
# - name: helper-argocd
#   repo: https://charts.stderr.at
#   valuesFile: values.yaml


helmGlobals:
  chartHome: ../../../charts
helmCharts:
- releaseName: mariadb
  namespace: default
  name: mariadb
  version: 0.1.0
  includeCRDs: false
  valuesInline:
    ingress:
      enabled: true