apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config-overlays
  namespace: argocd
spec:
  generators:
  - git:
      https://github.com/adhambbaker/k8-gitops.git
      abb-dev
      files:
        - path: "clusters/**/conf.yaml"
  template:
    metadata:
      name: "config-{{cluster.environment}}-{{cluster.name}}-overlay"
      labels:
        environment: "{{cluster.environment}}"
        cluster: "{{cluster.fqdn}}"
        region: "{{cluster.region}}"
        cloud: "{{cluster.cloud}}"
    spec:
      project: default
      source:
        https://github.com/adhambbaker/k8-gitops.git
        targetabb-dev
        path: clusters/{{cluster.environment}}/{{cluster.fqdn}}/overlay
      destination:
        server: "{{cluster.address}}"
      syncPolicy: {}
