apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-gitops-one-repo
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    # path: base
    repoURL: >-
      https://github.com/adhambbaker/k8-gitops.git
    targetRevision: one-repo
  syncPolicy: {}
