apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-clusters
  namespace: argocd
spec:
  argoServer:
    cluster: local-cluster
    argonamespace: argocd
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: vmware
    namespace: argocd