apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  annotations:
    bundling-component: gke-common-webhooks
    components.gke.io/component-name: gke-common-webhooks
    components.gke.io/component-version: 31.23.0-gke.8
    components.gke.io/layer: addon
  creationTimestamp: "2025-02-22T22:24:07Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: warden-scheduling.warden-policies.gke.io
  resourceVersion: "629"
  uid: d8c250f6-dbfa-4f88-b0aa-b6f19f8f1277
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    resourceRules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods/binding
      scope: '*'
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - bindings
      scope: '*'
  validations:
  - expression: request.userInfo.username == 'system:kube-scheduler' || !object.?target.name.orValue('').startsWith('gk3')
    message: Custom scheduling of pods to Autopilot nodes is not allowed.
status:
  observedGeneration: 1
  typeChecking: {}